### ISSUE TITLE
Nothing happens after login to apple music.

### ISSUE THREAD

**Issue by shynkevich-alex** [KoleMyers/apple-musickit-example#3]
I trying to generate music user token but nothing happens after login.

https://monosnap.com/file/3apdjSKniQXGaUALeva4qM3avZSRnV

**Comment by KoleMyers** [comment]
It may be something similar to [this](https://github.com/Musish/Musish/issues/243). They suggest changing your browsers language. I've run into region issues with the musickit library as well, so you could try changing regions with a vpn and see if it helps

**Comment by shynkevich-alex** [comment]
@KoleMyers Thank you a lot!
 I removed extra languages in chrome and it works for me now.
