### ISSUE TITLE
User Token returns undefined.

### ISSUE THREAD

**Issue by joshuaiz** [KoleMyers/apple-musickit-example#5]
First thanks for creating this - super helpful.

Got the repo installed and working and can get the server running. Logged in to Apple Music to generate a User Token and in Safari getting this:

![CleanShot 2021-02-17 at 23 45 03](https://user-images.githubusercontent.com/1096738/108322544-6f2b7580-717a-11eb-9a68-4509af621a3b.png)

![CleanShot 2021-02-17 at 23 45 30](https://user-images.githubusercontent.com/1096738/108322558-72befc80-717a-11eb-9a4a-b1aeea7f6be6.png)

And in Chrome getting this:

![CleanShot 2021-02-17 at 23 47 25](https://user-images.githubusercontent.com/1096738/108322593-81a5af00-717a-11eb-853a-7f1ab42582f1.png)

The `music.authorize()` line is generating an `Uncaught in promise -1` error:

```js
document.getElementById('login-btn').addEventListener('click', () => {
      /***
        Returns a promise which resolves with a music-user-token when a user successfully authenticates and authorizes
        https://developer.apple.com/documentation/musickitjs/musickit/musickitinstance/2992701-authorize
      ***/
      music.authorize().then(musicUserToken => {
        console.log(`Authorized, music-user-token: ${musicUserToken}`);
      });
    });

```

I'm on a new M1 MBP - could that be the issue? 

If that's not it, any other ideas?

I'm running macOS 11.2.1 (Big Sur)

**Comment by KoleMyers** [comment]
Can you catch and log the full error?

 I tried parsing through the `musickit.js` file trying to find anything about specific platform support but didn't see anything conclusive.

**Comment by joshuaiz** [comment]
@KoleMyers thanks for the reply. Tried adding a `catch` block and it is only returning `-1`.

Here are a couple screenshots, the first from Safari (which has some line numbers) and the second from Chrome:

Safari:
![CleanShot 2021-02-19 at 19 47 50](https://user-images.githubusercontent.com/1096738/108583270-3364ed00-72ed-11eb-88b9-7d121c6d9997.png)


Chrome:
![CleanShot 2021-02-19 at 19 48 35](https://user-images.githubusercontent.com/1096738/108583273-3a8bfb00-72ed-11eb-8d15-281699491fa0.png)


Let me know if there's anything else I can try to help debug. Thanks!

**Comment by KoleMyers** [comment]
Just to confirm you are able to get through the popup authentication flow right? The token just isn't being set afterward? I was able to get it running on safari and chrome on Big Sur 11.0.1. It's possible a recent update broke it though. 

Just a shot in the dark, do you have any custom language or region settings configured on your computer? It Could be something like what happened [here](https://github.com/KoleMyers/apple-musickit-example/issues/3) where having additional languages installed on a browser was causing issues. Since it's happening for you on both safari and chrome I doubt this is the cause though. 

If you could take a screen recording of the full flow it might help. It also may be worth posting in the [musickit forum](https://developer.apple.com/forums/tags/musickit/).

**Comment by joshuaiz** [comment]
@KoleMyers thanks for the reply.

Yes, was able to log in to Music app without issue. No custom language or region settings...I did see those issues as well.

Will take a screen recording of the flow later this eve and will take a look at the musickit forum.

Would love to get this solved.

**Comment by joshuaiz** [comment]
@KoleMyers I think I found the answer here: https://developer.apple.com/forums/thread/651895

In short, you need an active Apple Music subscription to access anything with `/me/` in the domain and I do not have one.

So, let me then rephrase what I am trying to do which is retrieve the current logged-in user's personal playlists in the Music app — not playlists containing Apple Music (paid) songs. 

Ultimately, i want to convert local Music app playlists to JSON. I know there are some web-based services that can do this but is there a way to do this via the API or another way to do this locally?

**Comment by joshuaiz** [comment]
Ended up signing up for Apple Music and was able to retrieve a user token so this is resolved.

For anyone else, accessing any user music library data requires an Apple Music account.
